name: hiroyuki_diet_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # App packages
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0

  # --- Ferry Packages ---
  ferry: ^0.16.0
  ferry_flutter: ^0.9.0
  gql_http_link: ^1.0.0
  gql_link: ^1.0.0+1
  gql_exec: ^1.0.0+1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation Packages ---
  build_runner: ^2.4.0
  ferry_generator: ^0.12.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/hiroyuki_room.PNG
    - assets/hiroyuki_gym.PNG

  uses-material-design: true